[project]
name = "projet-5-d-ployer-un-model"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "httpx2>=2.9.1",
    "joblib>=1.5.3",
    "pandas>=3.0.5",
    "psycopg2>=2.9.12",
    "pydantic>=2.13.4",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "python-dotenv>=1.2.2",
    "scikit-learn>=1.9.0",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.0",
]

# Paramétrage des tests
[tool.pytest.ini_options]
pythonpath = ["."]
# Options par défaut de : uv run pytest
# Les tests génèrent une erreur si la couverture de test est inférieure à 85%
# Le rapport HTML est généré automatiquement dans le dossier tests/coverage/htmlcov
addopts = "--cov=app --cov-report=term-missing --cov-fail-under=85 --cov-report=html:tests/coverage/htmlcov"

# Emplacement du fichier .coverage
[tool.coverage.run]
data_file = "tests/coverage/.coverage"